services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  nextjs-app:
    image: ${NEXTJS_IMAGE_NAME}
    container_name: ${NEXTJS_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile.dev
      args:
        NEXTJS_PORT: ${NEXTJS_PORT}
        # Use user id & group id in .env
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    user: ${USER_ID}:${GROUP_ID}
    restart: unless-stopped
    #ports:
    #  - ${NEXTJS_PORT_OUT}:${NEXTJS_PORT}
    volumes:
      - ./src:/app
      - dot_next:/app/.next
      - node_modules:/app/node_modules
      # Set the logins and groups identical to host environment
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      - NODE_ENV=development
    #env_file:
    #  - ./.env
    depends_on:
      - nginx

volumes:
  dot_next:
  node_modules: