services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  nextjs-app:
    image: ${NEXTJS_IMAGE_NAME}
    container_name: ${NEXTJS_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile.dev
      args:
        NEXTJS_PORT: ${NEXTJS_PORT}
    restart: unless-stopped
    #ports:
    #  - ${NEXTJS_PORT_OUT}:${NEXTJS_PORT}
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    #env_file:
    #  - ./.env
    depends_on:
      - nginx

volumes:
  node_modules: